language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1"
  - "2.2"
  - "2.3.0"
  - "jruby"
script: bundle exec rspec spec
before_install:
  - add-apt-repository -y ppa:moti-p/cc
  - apt-get update
  - apt-get -y --reinstall install imagemagick
  - gem install bundler
